### ISSUE TITLE
UTF-8 Support

### ISSUE THREAD

**Issue by vytux-com** [JustCarmen/fancy_gendex#1]
Hey Carmen,

Not sure if this is a problem with your module or a fault in the gendex file specification, 

My lithuanian tree characters are all malformed in the txt file.

Regards,
Vytautas

**Comment by JustCarmen** [comment]
I haven't been able to find any solution for this. I have tried all possible solutions without any success. I doubt the issue is in the module code but rather a problem of the gendex site.
