### ISSUE TITLE
gendex.txt (1.7.12)

### ISSUE THREAD

**Issue by phildtmm** [JustCarmen/fancy_gendex#12]
Creating the gendex.txt file in the webtrees root was not an issue prior to my migration to Fedora.  Now with the Fedora OS which uses SELinux for additional security creates other potential exposures if SELinux sets the context for the webtrees root to be read/write.  In this case, would it not be possible to allow the module to be configurable so that it could be written into the data directory and then manually copy it to the webtrees root?

**Comment by JustCarmen** [comment]
I will close this old post since I have decided to stop the development for this module.
