### ISSUE TITLE
Fancy Gendex not working in webtrees 1.7.8

### ISSUE THREAD

**Issue by HonkXL** [JustCarmen/fancy_gendex#7]
Since upgrading to webtrees 1.7.8 I got this error when updating the Gendex file.

/var/www/vhosts/weiland24.de/httpdocs/webtrees/modules_v3/fancy_gendex/app/FancyGendexClass.php:66 Class 'Zend_Filter_StringToUpper' not found #0 /modules_v3/fancy_gendex/app/FancyGendexClass.php:104 Error("Class 'Zend_Filter_StringToUpper' not found") #1 /modules_v3/fancy_gendex/app/FancyGendexClass.php:122 writeGendexChunks([Tree], [resource]) #2 /modules_v3/fancy_gendex/app/FancyGendexClass.php:133 writeGendexContent([resource]) #3 /modules_v3/fancy_gendex/app/FancyGendexClass.php:42 writeGendexFile('/var/www/vhosts/weiland24.de/h…', [resource]) #4 /modules_v3/fancy_gendex/module.php:73 createGendex() #5 /module.php:26 modAction('admin_config')

**Comment by fisharebest** [comment]
We stopped using the Zend library a while ago.

A quick look at the code suggests you could MySQL to do this
`SELECT UPPER(n_surname) AS n_surname`
