### ISSUE TITLE
request for less information in gendex file

### ISSUE THREAD

**Issue by Joppla** [JustCarmen/fancy_gendex#9]
Hello,

Thanks for making the Fancy Gendex Module.

Is it possible to make it possible to choose the items which will be included in the gendex file, like date of birth, place of birth, date of death, place of death. It can maybe done with a choosebox like for Replace_Chars. And for the dates possibility to choose between full layout (d M YY) or only the YEAR.

Thanks,
Jop

**Comment by JustCarmen** [comment]
Sorry, but I do not see any reason to not include this information in the Gendex file, The final search results from the search engine will lead back to the page of the person in question where this information can be easily viewed.

Moreover, the privacy settings in webtrees are taken into account when compiling the Gendex file. No information is included that is not publicly accessible.

**Comment by JustCarmen** [comment]
See comment https://github.com/JustCarmen/fancy_gendex/issues/9

**Comment by Joppla** [comment]
Erg jammer :-(
